// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxgzfmnnabambnuvrwxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Z3pmbW5uYWJhbWJudXZyd3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNzI0MjMsImV4cCI6MjA3MTg0ODQyM30.5frRXJ16ufwiaP7XlPu9XkHRCQwK8qHMWeTerxc5mM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});